// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ8f4H1KDdEgZC3AP7scTFS2vB0qa_zy4',
    appId: '1:122842032922:web:5b002b8b38c9240be75aa3',
    messagingSenderId: '122842032922',
    projectId: 'qnaapp-c9361',
    authDomain: 'qnaapp-c9361.firebaseapp.com',
    storageBucket: 'qnaapp-c9361.firebasestorage.app',
    measurementId: 'G-5GZ2L7DHZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_FEkXsvjlRgoUFe2yLf1zQmM4Ki36Bgw',
    appId: '1:122842032922:android:611d522a118f6154e75aa3',
    messagingSenderId: '122842032922',
    projectId: 'qnaapp-c9361',
    storageBucket: 'qnaapp-c9361.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3kDc1vjhqwt_m9oc-NmvujJnyLDAYhJ4',
    appId: '1:122842032922:ios:1426679cede3a782e75aa3',
    messagingSenderId: '122842032922',
    projectId: 'qnaapp-c9361',
    storageBucket: 'qnaapp-c9361.firebasestorage.app',
    iosBundleId: 'com.example.qnaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3kDc1vjhqwt_m9oc-NmvujJnyLDAYhJ4',
    appId: '1:122842032922:ios:1426679cede3a782e75aa3',
    messagingSenderId: '122842032922',
    projectId: 'qnaapp-c9361',
    storageBucket: 'qnaapp-c9361.firebasestorage.app',
    iosBundleId: 'com.example.qnaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ8f4H1KDdEgZC3AP7scTFS2vB0qa_zy4',
    appId: '1:122842032922:web:00a8acdb3c3df8e7e75aa3',
    messagingSenderId: '122842032922',
    projectId: 'qnaapp-c9361',
    authDomain: 'qnaapp-c9361.firebaseapp.com',
    storageBucket: 'qnaapp-c9361.firebasestorage.app',
    measurementId: 'G-31B39HMEMS',
  );
}
